// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbbrlmokqmcglhmstfod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiYnJsbW9rcW1jZ2xobXN0Zm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjUxMzIsImV4cCI6MjA3MDk0MTEzMn0.1mqStFmmoI-33Fq7WIH72U_jm8ud2gM7Rx8nKEBkS8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});